### ISSUE TITLE
[Taxonomy Tree]: Italian Translations tende and teli per bagno need updating

### ISSUE THREAD

**Issue by aleightizer** [Shopify/product-taxonomy#238]
### Taxonomy Field

Category

### Vertical

None

### Change Type

Other

### Issue

[Italian category ranslations](https://github.com/Shopify/product-taxonomy/blob/46e604a6c009d0071f123ae421c2109373c2dce5/data/localizations/categories/it.yml) are a bit inaccurate.

`Curtains` and `Drapes` become `tende` and `tende` instead of `tende` and `tendaggi`.

The `Towels` category is mistranslated to `teli per bagno` (bath towels) - which is a subcategory itself.

### Description

English:
``` 
    hg-3-74-1:
      name: Curtains & Drapes
    hg-3-74-1-1:
      name: Curtains
    hg-3-74-1-2:
      name: Drapes
```

Italian:
```
    hg-3-74-1:
      name: Tende e tendaggi
    hg-3-74-1-1:
      name: Tende
    hg-3-74-1-2:
      name: Tende
```

hg-3-74-1-2 should be `Tendaggi` (drapes)

English:
```
    hg-15-4:
      name: Towels
    hg-15-4-1:
      name: Bath Towels & Washcloths
    hg-15-4-1-1:
      name: Bath Towels
    hg-15-4-1-2:
      name: Washcloths
    hg-15-4-2:
      name: Beach Towels
    hg-15-4-3:
      name: Kitchen Towels
```

Italian:
```
    hg-15-4:
      name: Teli per bagno
    hg-15-4-1:
      name: Asciugamani
    hg-15-4-1-1:
      name: Asciugamani da bagno
    hg-15-4-1-2:
      name: Washcloths
    hg-15-4-2:
      name: Asciugamani da spiaggia
    hg-15-4-3:
      name: Asciugamani da cucina
```

hg-15-4 should be `Asciugamani`
hg-15-4-1 should be `Teli per bagno` or `Asciugamani da bagno e Washcloths`

### Video/Screenshot

Curtains & Drapes:
![](https://screenshot.click/10-31-c2mhq-sq9yl.png)

Curtains &... Curtains?:
![](https://screenshot.click/12-12-p32vi-do63l.png)

 Towels category:
 ![](https://screenshot.click/10-19-4k69e-iy0vp.png)

teli de bagno (bath towels):
![](https://screenshot.click/12-18-39a8n-560p7.png)
